// Site
export const SITE_LOADING = 'SITE_LOADING';
export const SITE_LOADED = 'SITE_LOADED';
export const SET_SIDEBAR_TOGGLER = 'SET_SIDEBAR_TOGGLER';

// Auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const ACTIVATING_USER = 'ACTIVATING_USER';
export const USER_ACTIVATED = 'USER_ACTIVATED';
export const ACTIVATION_FAILED = 'ACTIVATION_FAILED';

export const SOCIAL_AUTH_SUCCESS = 'SOCIAL_AUTH_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_UPDATED = 'USER_UPDATED';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REQUEST_LOADING = 'REQUEST_LOADING';
export const PASSWORD_UPDATE = 'PASSWORD_UPDATE';
export const REQUEST_PROCESSED = 'REQUEST_PROCESSED';

export const ADDRESS_ADDED = 'ADDRESS_ADDED';
export const ADDRESS_DELETED = 'ADDRESS_DELETED';
export const ADDRESS_UPDATED = 'ADDRESS_UPDATED';

// Auth - Verification
export const VERIFYING_PASSWORD_RESET = 'VERIFYING_PASSWORD_RESET';
export const VERIFIED_PASSWORD_RESET = 'VERIFIED_PASSWORD_RESET';
export const PASSWORD_RESET_VERIFICATION_ERROR = 'PASSWORD_RESET_VERIFICATION_ERROR';
export const PASSWORD_RESET_DONE = 'PASSWORD_RESET_DONE';

// Contact
export const CONTACTING = 'CONTACTING';
export const CONTACTED = 'CONTACTED';

// Categories
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';
// Orders
export const CURRENT_ORDER_LOADING = 'CURRENT_ORDER_LOADING';
export const GET_CURRENT_ORDER = 'GET_CURRENT_ORDER';
export const CURRENT_ORDER_ERROR = 'CURRENT_ORDER_ERROR';

export const QUANTITY_LOADING = 'QUANTITY_LOADING';
export const QUANTITY_CHANGED = 'QUANTITY_CHANGED';
export const QUANTITY_CHANGE_ERROR = 'QUANTITY_CHANGE_ERROR';

export const DELETE_LOADING = 'DELETE_LOADING';
export const DELETE_ORDER_ITEM = 'DELETE_ORDER_ITEM';
export const DELETE_ERROR = 'DELETE_ERROR';

export const CHECKOUT_LOADING = 'CHECKOUT_LOADING';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILED = 'CHECKOUT_FAILED';

export const CANCEL_ORDER = 'CANCEL_ORDER';

export const COMPLETE_ORDER_LOADING = 'COMPLETE_ORDER_LOADING';
export const COMPLETE_ORDER_SUCCESS = 'COMPLETE_ORDER_SUCCESS';
export const COMPLETE_ORDER_FAILED = 'COMPLETE_ORDER_FAILED';
// Sellers
export const SELLERS_LOADING = 'SELLERS_LOADING';
export const MORE_SELLERS_LOADING = 'MORE_SELLERS_LOADING';
export const GET_SELLERS = 'GET_SELLERS';
export const GET_MORE_SELLERS = 'GET_MORE_SELLERS';
export const SET_SELLERS_PAGE = 'SET_SELLERS_PAGE';
export const SELLERS_ERROR = 'SELLERS_ERROR';
export const FILTER_CUISINE = 'FILTER_CUISINE';
export const CLEAR_CUISINE = 'CLEAR_CUISINE';
export const FILTER_KEYWORDS = 'FILTER_KEYWORDS';
export const CLEAR_KEYWORDS = 'CLEAR_KEYWORDS';

// Seller
export const ALL_SELLERS_LOADING = 'ALL_SELLERS_LOADING';
export const GET_ALL_SELLERS = 'GET_ALL_SELLERS';
export const ALL_SELLERS_ERROR = 'ALL_SELLERS_ERROR';
export const SELLER_LOADING = 'SELLER_LOADING';
export const GET_SELLER = 'GET_SELLER';
export const SELLER_ERROR = 'SELLER_ERROR';
export const FILTER_COURSE = 'FILTER_COURSE';
// Products
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const MORE_PRODUCTS_LOADING = 'MORE_PRODUCTS_LOADING';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_MORE_PRODUCTS = 'GET_MORE_PRODUCTS';
export const SET_PRODUCTS_PAGE = 'SET_PRODUCTS_PAGE';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
// Product
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
// Admin
export const DASHBOARD_LOADING = 'DASHBOARD_LOADING';
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
export const DASHBOARD_DATA_ERROR = 'DASHBOARD_DATA_ERROR';

export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS';
export const ORDER_ITEMS_ERROR = 'ORDER_ITEMS_ERROR';

export const ORDERS_LOADING = 'ORDERS_LOADING';
export const MORE_ORDERS_LOADING = 'MORE_ORDERS_LOADING';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_MORE_ORDERS = 'GET_MORE_ORDERS';
export const ORDERS_ERROR = 'ORDERS_ERROR';
export const SET_ORDERS_PAGE = 'SET_ORDERS_PAGE';
export const FILTER_CURRENT_ONLY = 'FILTER_CURRENT_ONLY';

export const ORDER_LOADING = 'ORDER_LOADING';
export const GET_ORDER = 'GET_ORDER';
export const ORDER_ERROR = 'ORDER_ERROR';

export const MANAGER_ORDER_LOADING = 'ORDER_LOADING';
export const GET_MANAGER_ORDER = 'GET_ORDER';
export const MANAGER_ORDER_ERROR = 'ORDER_ERROR';
export const REVIEW_ORDER = 'REVIEW_ORDER';

export const ORDER_ITEM_LOADING = 'ORDER_ITEM_LOADING';
export const GET_ORDER_ITEM = 'GET_ORDER_ITEM';
export const ORDER_ITEM_ERROR = 'ORDER_ITEM_ERROR';
export const REVIEW_PRODUCT = 'REVIEW_PRODUCT';
export const REVIEW_PRODUCT_ORDER = 'REVIEW_PRODUCT_ORDER';

export const GET_MANAGER_ORDERS = 'GET_MANAGER_ORDERS';
export const MANAGER_ORDERS_ERROR = 'MANAGER_ORDERS_ERROR';

export const CLAIM_ORDER = 'CLAIM_ORDER';
export const RIDER_CANCEL_ORDER = 'RIDER_CANCEL_ORDER';
export const RIDER_UNCLAIM_ORDER = 'RIDER_UNCLAIM_ORDER';
export const PREPARE_ORDER = 'PREPARE_ORDER';

export const DELIVER_ORDER_ITEM = 'DELIVER_ORDER_ITEM';
export const DELIVER_ORDER = 'DELIVER_ORDER';

export const PICKUP_ORDER_ITEM = 'PICKUP_ORDER_ITEM';
export const PICKUP_ORDER = 'PICKUP_ORDER';

export const TOGGLING_IS_PUBLISHED = 'TOGGLING_IS_PUBLISHED';
export const TOGGLED_IS_PUBLISHED = 'TOGGLED_IS_PUBLISHED';
export const IS_PUBLISHED_ERROR = 'IS_PUBLISHED_ERROR';

export const SYNC_ORDER = 'SYNC_ORDER';